### ISSUE TITLE
[Bug]: install failed

### ISSUE THREAD

**Issue by qhoirulanwar** [coderflexx/filament-turnstile#13]
### What happened?

install failed

### How to reproduce the bug

![image](https://github.com/coderflexx/filament-turnstile/assets/22901097/9d47f68c-9b22-4d0e-9d1c-8dfdeb14febb)

### Package Version

2.1

### PHP Version

8.3

### Laravel Version

11.x

### Which operating systems does with happen with?

macOS

### Notes

Is this a bug when using Laravel 11?

**Comment by ousid** [comment]
Hi, @qhoirulanwar 

This package still does not support `Laravel 11` yet, will work on it in the next few hours.
