### ISSUE TITLE
[Bug]: add support for Filament v3

### ISSUE THREAD

**Issue by alphaolomi** [coderflexx/filament-turnstile#3]
### What happened?

cant use Filament v3

### How to reproduce the bug

install on ilament v3

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10.*

**Comment by ousid** [comment]
Hey @alphaolomi 

You can upgrade the package in your `composer.json` to use the latest version that support __Filament V3__ now.

Enjoy!

**Comment by alphaolomi** [comment]
Thank you @ousid 🙏
